name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_mock_adapter: ^0.6.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
   sdk: flutter
   
  flutter_lints: ^5.0.0
  test: ^1.25.8
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
